//Categories
INSERT INTO `category`(`category`) VALUES ("Databases");
INSERT INTO `category`(`category`) VALUES ("Java");
INSERT INTO `category`(`category`) VALUES ("PHP");
INSERT INTO `category`(`category`) VALUES ("C#");
INSERT INTO `category`(`category`) VALUES ("Python");
INSERT INTO `category`(`category`) VALUES ("R");

//Subcategories
INSERT INTO sub_category(sub_category, category_id) VALUES ("SQL", 1);
INSERT INTO sub_category(sub_category, category_id) VALUES ("NoSQL", 1);
INSERT INTO sub_category(sub_category, category_id) VALUES ("Spring", 2);
INSERT INTO sub_category(sub_category, category_id) VALUES ("Struts", 2);
INSERT INTO sub_category(sub_category, category_id) VALUES ("Laravel", 3);
INSERT INTO sub_category(sub_category, category_id) VALUES ("CodeIgniter", 3);
INSERT INTO sub_category(sub_category, category_id) VALUES (".net", 4);
INSERT INTO sub_category(sub_category, category_id) VALUES ("LINQ", 4);
INSERT INTO sub_category(sub_category, category_id) VALUES ("Django", 5);
INSERT INTO sub_category(sub_category, category_id) VALUES ("Pandas", 5);
INSERT INTO sub_category(sub_category, category_id) VALUES ("RStudio", 6);
INSERT INTO sub_category(sub_category, category_id) VALUES ("TidyVerse", 6);

//Questions
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (91,1, "What is the difference between a stack and queue?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (92,1, "Which group contains all official types of JIT compilations?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (93,1, "What is Kestrel?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (94,1, " When would you use asynchronous actions?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (95,1, "When you define an abstract method, how do you use it in a derived class?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (96, 2, "Which code do you use if you want to trigger a garbage collection in .NET?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (97, 2, "What makes a strong-named assembly?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (98, 2, "Which is a set of features that extends the query capabilities of the .NET language syntax by adding sets of new standard query operators that allow data manipulation, regardless of the data source?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (99, 2, " What is the single responsibility principle?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (100, 2, "Assuming y is a value type, which is an example of boxing?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (101, 3, "You want to encapsulate a command request as an object. Which design pattern best fits this objective?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (102,3, "You want to create a class of which only a single instance can exist. Which design pattern best fits this objective?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (103, 3, "What do code contracts do?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (104,3, "Which is NOT true about a constant variable?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (105,3, "Which choice creates an 8-tuple containing prime numbers that are less than 20?", 7);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (106,1, "How would you write code for an integer property called Age with a getter and setter?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (107,1, "When using a thread pool what happens to a given thread after it finishes its task?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (108,1, "Which choice represents a class that inherits behavior from a base class?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (109,1, "What does operator overloading allow you to do?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (110,1, "What it the main purpose of LINQ?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (111,2, "What is the correct syntax for a new generic list of strings named contacts?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (112,2, "What character would you use to start a regular expression pattern at a word boundary?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (113,2, "You're dealing with multiple assemblies in your program, but are worried about memory allocation. At what point in the program life cycle are assemblies loaded into memory?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (114,2, "When would you use generics in your code?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (115,2, "What is the difference between an anonymous type and a regular data type?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (116,3, "Lambda expressions are often used in tandem with which of the following?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (117,3, "How does the async keyword work?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (118,3, "How are C# classses limited?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (119,3, "What are the four keywords associated with exception handling in C#?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (120,3, "What is the difference between finally and finalize blocks?", 8);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (121,1, "To cache your entire site for an application in Django, you add all except which of these settings?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (122,1, "In which programming language is Django written?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (123,1, "To automatically provide a value for a field, or to do validation that requires access to more than a single field, you should override the ___ method in the ___ class.", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (124,1, "How do you determine at startup time if a piece of middleware should be used?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (125,1, "How do you turn off Django’s automatic HTML escaping for part of a web page?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (126,2, "Which step would NOT help you troubleshoot the error django-admin: command not found?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (127,2, "Every time a user is saved, their quiz_score needs to be recalculated. Where might be an ideal place to add this logic?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (128,2, "What is the correct way to begin a class called Rainbow in Python?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (129, 2, "You have inherited a Django project and need to get it running locally. It comes with a requirements.txt file containing all its dependencies. Which command should you use?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (130, 2, "Which best practice is NOT relevant to migrations?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (131, 3, "What will this URL pattern match? url(r'^$', views.hello)", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (132, 3, "Django's class-based generic views provide which classes that implement common web development tasks?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (133, 3, "What is the correct way to make a variable available to all of your templates?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (134, 3, "You want to create a page that allows editing of two classes connected by a foreign key (e.g., a question and answer that reside in separate tables). What Django feature can you use?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (135, 3, "Which function of Django's Form class will render a form's fields as a series of tags?", 9);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (136, 1, "What happens when you use the build-in function any() on a list?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (137, 1, "What data structure does a binary tree degenerate to if it isn't balanced properly?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (138, 1, "What statement about static methods is true?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (139, 1, "What built-in list method would you use to remove items from a list?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (140, 1, "What is one of the most common use of Python's sys library?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (141, 2, "What is the runtime of accessing a value in a dictionary by using its key?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (142, 2, "What built-in Python data type is commonly used to represent a stack?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (143, 2, "What is the correct syntax for defining a class called Game, if it inherits from a parent class called LogicGame?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (144, 2, " Which of these is NOT a characteristic of namedtuples?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (145, 2, "What is an instance method?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (146, 3, "Which statement does NOT describe the object-oriented programming concept of encapsulation?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (147, 3, "What built-in Python data type is best suited for implementing a queue?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (148, 3, "What is the correct syntax for instantiating a new object of the type Game?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (149, 3, "What does the built-in map() function do?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (150, 3, "Which collection type is used to associate values with unique keys?", 10);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (151, 1, "How does a matrix differ from a data frame?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (152, 1, "What value does this statement return? unclass(as.Date('1971-01-01'))", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (153, 1, "What do you use to take an object such as a data frame out of the workspace?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (154, 1, "The variable height is a numeric vector in the code below. Which statement returns the value 35?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (155, 1, "Which choice does R regard as an acceptable name for a variable?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (156, 2, "What is the principal difference between an array and a matrix?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (157, 2, "Which is not a property of lists and vectors?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (158, 2, "Which function displays the first five rows of the data frame named pizza?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (159, 2, "You accidentally display a large data frame on the R console, losing all the statements you entered during the current session. What is the best way to get the prior 25 statements back?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (160, 2, "How does a vector differ from a list?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (161, 3, "What statement shows the objects on your workspace?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (162, 3, "What function joins two or more column vectors to form a data frame?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (163, 3, "Two variable in the mydata data frame are named Var1 and Var2. How do you tell a bivariate function, such as cor.test, which two variables you want to analyze?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (164, 3, "How to name rows and columns in DataFrames and Matrices F in R?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (165, 3, "Which function in R combines differents values into a single object?", 11);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (166, 1, "what mean 'geoms' in ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (167, 1, "what mean 'aes' in ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (168, 1, "What is ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (169, 1, "What is the geom reference for a Scatter Plot?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (170, 1, "What is the geom reference for a Histogram?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (171, 2, "When to use a Histogram?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (172, 2, "When to use a Correlogram?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (173, 2, "When to use a Scatter Plot?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (174, 2, "What are the Scales in ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (175, 2, "What is Facetting in ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (176, 3, "Which strings could be returned by the function ls(path = ^V)?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (177, 3, "A list can contain a list as an element. MyList has five columns, and the third column''s item is a list of three items. How do you put all seven values in MyList into a single vector?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (178, 3, "What is the tidyverse library for animate ggplot2 plots?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (179, 3, "What is the tidyverse library who allows the use of various filters and shaders on ggplot2?", 12);
INSERT INTO question(id, difficulty_level, question, sub_category_id) VALUES (180, 3, "How to plot a data set in single command ?", 12);


//Answers
INSERT INTO answer(answer, correct, question_id) VALUES ("Queues process value types by a top-down hierarchy - first in, first out (FIFO). Stacks follow this principle and insert items from the lower end while deleting ones from the top - last in, first-out (LIFO)",0,91);
INSERT INTO answer(answer, correct, question_id) VALUES ("Queues process value types by a top-down hierarchy-last in, first-out (LIFO). Stacks follow this principle and insert items from the lower end while deleting ones from the top-first in, first-out (FIFO)",0,91);
INSERT INTO answer(answer, correct, question_id) VALUES ("Stacks process value types by a top-down hierarchy - last in, first-out (LIFO). Queues follow this principle and insert items from the lower end while deleting ones from the top - first in, first-out (FIFO)",1,91);
INSERT INTO answer(answer, correct, question_id) VALUES ("Stacks process value types by a top-down hierarchy-first in, first out (FIFO). Queues follow this principle and insert items from the lower end while deleting ones from the top-last in, first-out (LIFO)",0,91);
INSERT INTO answer(answer, correct, question_id) VALUES ("Pre-JIT, Quick-JIT, Coll-JIT",0,92);
INSERT INTO answer(answer, correct, question_id) VALUES ("Before-JIT, Quick-JIT, Cool-JIT",0,92);
INSERT INTO answer(answer, correct, question_id) VALUES ("Pre-JIT, Quick-JIT, Normal-JIT",0,92);
INSERT INTO answer(answer, correct, question_id) VALUES ("Pre-JIT, Econo-JIT, Normal-JIT",1,92);
INSERT INTO answer(answer, correct, question_id) VALUES ("an iOS web server initially that was later designed to work with .NET Core",0,93);
INSERT INTO answer(answer, correct, question_id) VALUES ("a cross-platform web server ASP.NET Core that is included by default in ASP.NET Core project templates** <= Correct",1,93);
INSERT INTO answer(answer, correct, question_id) VALUES ("a cross-platform, open-source web server that starts up web APIs",0,93);
INSERT INTO answer(answer, correct, question_id) VALUES ("a free and open-source cross-platform web server software that can communicate with IIS",0,93);
INSERT INTO answer(answer, correct, question_id) VALUES ("to release the quest thread of a I/O operation",0,94);
INSERT INTO answer(answer, correct, question_id) VALUES ("to capture the request thread of a I/O operation",0,94);
INSERT INTO answer(answer, correct, question_id) VALUES ("to avoid blocking the request thread while waits for an I/O operation",1,94);
INSERT INTO answer(answer, correct, question_id) VALUES ("to block the request thread if it waits for an I/O operation",0,94);
INSERT INTO answer(answer, correct, question_id) VALUES ("Abstract methods cannot be used in derived classes.",0,95);
INSERT INTO answer(answer, correct, question_id) VALUES ("In your derived class, overload the method.",0,95);
INSERT INTO answer(answer, correct, question_id) VALUES ("In your derived class, override the method.",1,95);
INSERT INTO answer(answer, correct, question_id) VALUES ("In your derived class, declare the method as virtual.",0,95);
INSERT INTO answer(answer, correct, question_id) VALUES ("Garbage.CleanUp();",0,96);
INSERT INTO answer(answer, correct, question_id) VALUES ("System.GC.Clear();",0,96);
INSERT INTO answer(answer, correct, question_id) VALUES ("System.GC.Collect();",1,96);
INSERT INTO answer(answer, correct, question_id) VALUES ("Garbage.Collect();",0,96);
INSERT INTO answer(answer, correct, question_id) VALUES ("an assembly with the version specified",0,97);
INSERT INTO answer(answer, correct, question_id) VALUES ("a signed assembly",1,97);
INSERT INTO answer(answer, correct, question_id) VALUES ("an assembly with culture information",0,97);
INSERT INTO answer(answer, correct, question_id) VALUES ("an assembly with the name marked as important",0,97);
INSERT INTO answer(answer, correct, question_id) VALUES ("XML",0,98);
INSERT INTO answer(answer, correct, question_id) VALUES ("C#",0,98);
INSERT INTO answer(answer, correct, question_id) VALUES ("LINQ",1,98);
INSERT INTO answer(answer, correct, question_id) VALUES ("XAML",0,98);
INSERT INTO answer(answer, correct, question_id) VALUES ("Software entities should be open for extension, but closed for modification.",0,99);
INSERT INTO answer(answer, correct, question_id) VALUES ("Entities must depend on abstractions, not on concrete implementations.",0,99);
INSERT INTO answer(answer, correct, question_id) VALUES ("Objects in a program should be repleaceble with instances of their subtypes without altering the correctness of that programm.",0,99);
INSERT INTO answer(answer, correct, question_id) VALUES ("A class should have only a single responsibility - that is, only changes to one part of the software's specification should be able to affect the specification of the class.",1,99);
INSERT INTO answer(answer, correct, question_id) VALUES ("y = (int)thisObject;",0,100);
INSERT INTO answer(answer, correct, question_id) VALUES ("int y = 3;",0,100);
INSERT INTO answer(answer, correct, question_id) VALUES ("y = (int)thisObject=;3;",0,100);
INSERT INTO answer(answer, correct, question_id) VALUES ("object thisObject = y;",1,100);
INSERT INTO answer(answer, correct, question_id) VALUES ("Command",1,101);
INSERT INTO answer(answer, correct, question_id) VALUES ("Iterator",0,101);
INSERT INTO answer(answer, correct, question_id) VALUES ("Facade",0,101);
INSERT INTO answer(answer, correct, question_id) VALUES ("Observer",0,101);
INSERT INTO answer(answer, correct, question_id) VALUES ("Adapter",0,102);
INSERT INTO answer(answer, correct, question_id) VALUES ("Singleton",1,102);
INSERT INTO answer(answer, correct, question_id) VALUES ("Bridge",0,102);
INSERT INTO answer(answer, correct, question_id) VALUES ("Decorator",0,102);
INSERT INTO answer(answer, correct, question_id) VALUES ("Code contracts are data structures that can operate on demand per requirements.",0,103);
INSERT INTO answer(answer, correct, question_id) VALUES ("Code contracts provide a way to specify preconditions, postconditions, and object invariants in your code.",1,103);
INSERT INTO answer(answer, correct, question_id) VALUES ("Code contracts contain definitions for a group of related functionalities that a class or a struct can implement.",0,103);
INSERT INTO answer(answer, correct, question_id) VALUES ("Code contracts contain data structures for a group of related functionalities that a class or a struct can implement.",0,103);
INSERT INTO answer(answer, correct, question_id) VALUES ("At compile time, the value is evaluated.",0,104);
INSERT INTO answer(answer, correct, question_id) VALUES ("Only at declaration can it be initialized.",0,104);
INSERT INTO answer(answer, correct, question_id) VALUES ("At runtime, its value is evaluated.",1,104);
INSERT INTO answer(answer, correct, question_id) VALUES ("It cannot be static.",0,104);
INSERT INTO answer(answer, correct, question_id) VALUES ("var primes = Tuple.Create(2, 3, 5, 7, 11, 13, 17, 19);",1,105);
INSERT INTO answer(answer, correct, question_id) VALUES ("var primes = Tuple.Create(2, 3, 5, 7, 11, 13, 17, 21);",0,105);
INSERT INTO answer(answer, correct, question_id) VALUES ("var primes = Tuple.Make(2, 3, 5, 7, 11, 13, 17, 20);",0,105);
INSERT INTO answer(answer, correct, question_id) VALUES ("var primes = Tuple.Make(2, 3, 5, 7, 11, 13, 17, 19);",0,105);
INSERT INTO answer(answer, correct, question_id) VALUES ("public int Age { get - set }",0,106);
INSERT INTO answer(answer, correct, question_id) VALUES ("public int Age: get set;",0,106);
INSERT INTO answer(answer, correct, question_id) VALUES ("public int Age (get, set );",0,106);
INSERT INTO answer(answer, correct, question_id) VALUES ("public int Age { get; set; }",1,106);
INSERT INTO answer(answer, correct, question_id) VALUES ("The thread is destroyed and memory is freed up.",0,107);
INSERT INTO answer(answer, correct, question_id) VALUES ("The thread runs in loop until the next assignment.",0,107);
INSERT INTO answer(answer, correct, question_id) VALUES ("The thread goes inactive in the background and waits for garbage collection.",1,107);
INSERT INTO answer(answer, correct, question_id) VALUES ("The thread returns to the pool for reuse.",0,107);
INSERT INTO answer(answer, correct, question_id) VALUES ("a second base class",0,108);
INSERT INTO answer(answer, correct, question_id) VALUES ("a revised class",0,108);
INSERT INTO answer(answer, correct, question_id) VALUES ("a derived class",1,108);
INSERT INTO answer(answer, correct, question_id) VALUES ("a parent class",0,108);
INSERT INTO answer(answer, correct, question_id) VALUES ("hide built-in operatores when necessary",0,109);
INSERT INTO answer(answer, correct, question_id) VALUES ("add methods to be interpreted by the compiler at runtime",0,109);
INSERT INTO answer(answer, correct, question_id) VALUES ("define how enums and other primitive value types work within the rest of the application",0,109);
INSERT INTO answer(answer, correct, question_id) VALUES ("define custom functionality for common operators like addition and equality",1,109);
INSERT INTO answer(answer, correct, question_id) VALUES ("to delete duplicate data",0,110);
INSERT INTO answer(answer, correct, question_id) VALUES ("to bind namespaces and assemblies",0,110);
INSERT INTO answer(answer, correct, question_id) VALUES ("to query and transform data",1,110);
INSERT INTO answer(answer, correct, question_id) VALUES ("to connect assemblies",0,110);
INSERT INTO answer(answer, correct, question_id) VALUES ("public List contacts = new List();",0,111);
INSERT INTO answer(answer, correct, question_id) VALUES ("public List(string names) contacts = new List(string names)();",0,111);
INSERT INTO answer(answer, correct, question_id) VALUES ("var contacts = new List();",1,111);
INSERT INTO answer(answer, correct, question_id) VALUES ("var contacts = new List(string);",0,111);
INSERT INTO answer(answer, correct, question_id) VALUES ("d",0,112);
INSERT INTO answer(answer, correct, question_id) VALUES ("\a",0,112);
INSERT INTO answer(answer, correct, question_id) VALUES ("\b",1,112);
INSERT INTO answer(answer, correct, question_id) VALUES ("\w",0,112);
INSERT INTO answer(answer, correct, question_id) VALUES ("at runtime",0,113);
INSERT INTO answer(answer, correct, question_id) VALUES ("at compile time",0,113);
INSERT INTO answer(answer, correct, question_id) VALUES ("only when required",1,113);
INSERT INTO answer(answer, correct, question_id) VALUES ("only when programmatically loaded",0,113);
INSERT INTO answer(answer, correct, question_id) VALUES ("to increase code performance",0,114);
INSERT INTO answer(answer, correct, question_id) VALUES ("all of these answers",1,114);
INSERT INTO answer(answer, correct, question_id) VALUES ("when code reuse is a priority",0,114);
INSERT INTO answer(answer, correct, question_id) VALUES ("when type safety is important",0,114);
INSERT INTO answer(answer, correct, question_id) VALUES ("Anonymous types don't have type names",1,115);
INSERT INTO answer(answer, correct, question_id) VALUES ("Anonymous types can only be static",0,115);
INSERT INTO answer(answer, correct, question_id) VALUES ("Anonymous types can be used only in struts",0,115);
INSERT INTO answer(answer, correct, question_id) VALUES ("Anonymous types don't work with LINQ.",0,115);
INSERT INTO answer(answer, correct, question_id) VALUES ("Namespaces",0,116);
INSERT INTO answer(answer, correct, question_id) VALUES ("LINQ",1,116);
INSERT INTO answer(answer, correct, question_id) VALUES ("Type Aliasing",0,116);
INSERT INTO answer(answer, correct, question_id) VALUES ("Assemblies",0,116);
INSERT INTO answer(answer, correct, question_id) VALUES ("It allows access to asynchronous methods in the C# API",0,117);
INSERT INTO answer(answer, correct, question_id) VALUES ("It allows thread pooling and synchronous processes in static classes.",0,117);
INSERT INTO answer(answer, correct, question_id) VALUES ("It allows the await keyword to be used in a method",1,117);
INSERT INTO answer(answer, correct, question_id) VALUES ("It allows access to synchronous methods in the C# API",0,117);
INSERT INTO answer(answer, correct, question_id) VALUES ("They do not support multiple inheritance.",1,118);
INSERT INTO answer(answer, correct, question_id) VALUES ("They support multiple inheritance.",0,118);
INSERT INTO answer(answer, correct, question_id) VALUES ("They can have only a set number of properties.",0,118);
INSERT INTO answer(answer, correct, question_id) VALUES ("They can have only a set number of methods.",0,118);
INSERT INTO answer(answer, correct, question_id) VALUES ("try, catch, valid, invalid",0,119);
INSERT INTO answer(answer, correct, question_id) VALUES ("try, valid, finally, throw",0,119);
INSERT INTO answer(answer, correct, question_id) VALUES ("try, catch, finally, throw",1,119);
INSERT INTO answer(answer, correct, question_id) VALUES ("finally, throw, valid, invalid",0,119);
INSERT INTO answer(answer, correct, question_id) VALUES ("The finally block is called during the execution of a try and catch block, while the finalize method is called after garbage collection.",0,120);
INSERT INTO answer(answer, correct, question_id) VALUES ("The finally block is called after the execution of a try and catch block, while the finalize method is called just before garbage collection.",1,120);
INSERT INTO answer(answer, correct, question_id) VALUES ("The finalize block is called before the execution of a try and catch block, while the finally method is called just before garbage collection.",0,120);
INSERT INTO answer(answer, correct, question_id) VALUES ("The finalize block is called during the execution of a try and catch block, while the finally method is called after garbage collection.",0,120);
INSERT INTO answer(answer, correct, question_id) VALUES ("django.middleware.common.CommonMiddleware",0,121);
INSERT INTO answer(answer, correct, question_id) VALUES ("django.middleware.cache.UpdateCacheMiddleware",0,121);
INSERT INTO answer(answer, correct, question_id) VALUES ("django.middleware.cache.FetchFromCacheMiddleware",0,121);
INSERT INTO answer(answer, correct, question_id) VALUES ("django.middleware.cache.AcceleratedCacheMiddleware",1,121);
INSERT INTO answer(answer, correct, question_id) VALUES ("C++",0,122);
INSERT INTO answer(answer, correct, question_id) VALUES ("Java",0,122);
INSERT INTO answer(answer, correct, question_id) VALUES ("Python",1,122);
INSERT INTO answer(answer, correct, question_id) VALUES ("Ruby",0,122);
INSERT INTO answer(answer, correct, question_id) VALUES ("validate(); Model",0,123);
INSERT INTO answer(answer, correct, question_id) VALUES ("group(); Model",0,123);
INSERT INTO answer(answer, correct, question_id) VALUES ("validate(); Form",0,123);
INSERT INTO answer(answer, correct, question_id) VALUES ("clean(); Field",1,123);
INSERT INTO answer(answer, correct, question_id) VALUES ("Raise MiddlewareNotUsed in the init function of your middleware.",1,124);
INSERT INTO answer(answer, correct, question_id) VALUES ("Implement the not_used method in your middleware class.",0,124);
INSERT INTO answer(answer, correct, question_id) VALUES ("List the middleware beneath an entry of django.middleware.IgnoredMiddleware.",0,124);
INSERT INTO answer(answer, correct, question_id) VALUES ("Write code to remove the middleware from the settings in [app]/init.py.",0,124);
INSERT INTO answer(answer, correct, question_id) VALUES ("Place that section between paragraph tags containing the autoescape=off switch.",0,125);
INSERT INTO answer(answer, correct, question_id) VALUES ("Wrap that section between { percentage mark autoescape off percentage mark} and {percentage mark endautoescape percentage mark} tags.",0,125);
INSERT INTO answer(answer, correct, question_id) VALUES ("Wrap that section between {percentage mark autoescapeoff percentage mark} and {percentage mark endautoescapeoff percentage mark} tags.",0,125);
INSERT INTO answer(answer, correct, question_id) VALUES ("You don't need to do anything—autoescaping is off by default.",1,125);
INSERT INTO answer(answer, correct, question_id) VALUES ("Check that the bin folder inside your Django directory is on your system path.",0,126);
INSERT INTO answer(answer, correct, question_id) VALUES ("Make sure you have activated the virtual environment you have set up containing Django.",0,126);
INSERT INTO answer(answer, correct, question_id) VALUES ("Check that you have installed Django.",0,126);
INSERT INTO answer(answer, correct, question_id) VALUES ("Make sure that you have created a Django project.",1,126);
INSERT INTO answer(answer, correct, question_id) VALUES ("template",0,127);
INSERT INTO answer(answer, correct, question_id) VALUES ("model",1,127);
INSERT INTO answer(answer, correct, question_id) VALUES ("database",0,127);
INSERT INTO answer(answer, correct, question_id) VALUES ("view",0,127);
INSERT INTO answer(answer, correct, question_id) VALUES ("Rainbow {}",0,128);
INSERT INTO answer(answer, correct, question_id) VALUES ("export Rainbow:",0,128);
INSERT INTO answer(answer, correct, question_id) VALUES ("class Rainbow:",1,128);
INSERT INTO answer(answer, correct, question_id) VALUES ("def Rainbow:",0,128);
INSERT INTO answer(answer, correct, question_id) VALUES ("django-admin startproject requirements.txt",0,129);
INSERT INTO answer(answer, correct, question_id) VALUES ("python install -r requirements.txt",0,129);
INSERT INTO answer(answer, correct, question_id) VALUES ("pip install -r requirements.txt",1,129);
INSERT INTO answer(answer, correct, question_id) VALUES ("pip install Django",0,129);
INSERT INTO answer(answer, correct, question_id) VALUES ("To make sure that your migrations are up to date, you should run updatemigrations before running your tests.",1,130);
INSERT INTO answer(answer, correct, question_id) VALUES ("You should back up your production database before running a migration.",0,130);
INSERT INTO answer(answer, correct, question_id) VALUES ("Your migration code should be under source control.",0,130);
INSERT INTO answer(answer, correct, question_id) VALUES ("If a project has a lot of data, you should test against a staging copy before running the migration on production.",0,130);
INSERT INTO answer(answer, correct, question_id) VALUES ("a string beginning with the letter Ra string beginning with the letter R",0,131);
INSERT INTO answer(answer, correct, question_id) VALUES ("an empty string at the server root",1,131);
INSERT INTO answer(answer, correct, question_id) VALUES ("a string containing ^ and $a string containing ^ and $",0,131);
INSERT INTO answer(answer, correct, question_id) VALUES ("an empty string anywhere in the URLan empty string anywhere in the URL",0,131);
INSERT INTO answer(answer, correct, question_id) VALUES ("concrete",0,132);
INSERT INTO answer(answer, correct, question_id) VALUES ("thread-safe",0,132);
INSERT INTO answer(answer, correct, question_id) VALUES ("abstract",1,132);
INSERT INTO answer(answer, correct, question_id) VALUES ("dynamic",0,132);
INSERT INTO answer(answer, correct, question_id) VALUES ("Set a session variable.",0,133);
INSERT INTO answer(answer, correct, question_id) VALUES ("Use a global variable.",0,133);
INSERT INTO answer(answer, correct, question_id) VALUES ("Add a dictionary to the template context.",0,133);
INSERT INTO answer(answer, correct, question_id) VALUES ("Use RequestContext.",1,133);
INSERT INTO answer(answer, correct, question_id) VALUES ("actions",1,134);
INSERT INTO answer(answer, correct, question_id) VALUES ("admin",0,134);
INSERT INTO answer(answer, correct, question_id) VALUES ("mezcal",0,134);
INSERT INTO answer(answer, correct, question_id) VALUES ("inlines",0,134);
INSERT INTO answer(answer, correct, question_id) VALUES ("show_fields()",0,135);
INSERT INTO answer(answer, correct, question_id) VALUES ("as_p()",1,135);
INSERT INTO answer(answer, correct, question_id) VALUES ("as_table()",0,135);
INSERT INTO answer(answer, correct, question_id) VALUES ("fields()",0,135);
INSERT INTO answer(answer, correct, question_id) VALUES ("The any() function will randomly return any item from the list.",0,136);
INSERT INTO answer(answer, correct, question_id) VALUES ("The any() function returns True if any item in the list evaluates to True. Otherwise, it returns False.",1,136);
INSERT INTO answer(answer, correct, question_id) VALUES ("The any() function takes as arguments the list to check inside, and the item to check for. If any of the items in the list match the item to check for, the function returns True.",0,136);
INSERT INTO answer(answer, correct, question_id) VALUES ("The any() function returns a Boolean value that answers the question Are there any items in this list?",0,136);
INSERT INTO answer(answer, correct, question_id) VALUES ("linked list",1,137);
INSERT INTO answer(answer, correct, question_id) VALUES ("queue",0,137);
INSERT INTO answer(answer, correct, question_id) VALUES ("set",0,137);
INSERT INTO answer(answer, correct, question_id) VALUES ("OrderedDict",0,137);
INSERT INTO answer(answer, correct, question_id) VALUES ("Static methods are called static because they always return None.",0,138);
INSERT INTO answer(answer, correct, question_id) VALUES ("Static methods can be bound to either a class or an instance of a class.",0,138);
INSERT INTO answer(answer, correct, question_id) VALUES ("Static methods serve mostly as utility methods or helper methods, since they can't access or modify a class's state.",1,138);
INSERT INTO answer(answer, correct, question_id) VALUES ("Static methods can access and modify the state of a class or an instance of a class.",0,138);
INSERT INTO answer(answer, correct, question_id) VALUES (".delete() method",0,139);
INSERT INTO answer(answer, correct, question_id) VALUES ("pop(my_list)",0,139);
INSERT INTO answer(answer, correct, question_id) VALUES ("del(my_list)",0,139);
INSERT INTO answer(answer, correct, question_id) VALUES (".pop() method",1,139);
INSERT INTO answer(answer, correct, question_id) VALUES ("to capture command-line arguments given at a file's runtime",1,140);
INSERT INTO answer(answer, correct, question_id) VALUES ("to connect various systems, such as connecting a web front end, an API service, a database, and a mobile app",0,140);
INSERT INTO answer(answer, correct, question_id) VALUES ("to take a snapshot of all the packages and libraries in your virtual environment",0,140);
INSERT INTO answer(answer, correct, question_id) VALUES ("to scan the health of your Python ecosystem while inside a virtual environment",0,140);
INSERT INTO answer(answer, correct, question_id) VALUES ("O(n), also called linear time.",0,141);
INSERT INTO answer(answer, correct, question_id) VALUES ("O(log n), also called logarithmic time.",0,141);
INSERT INTO answer(answer, correct, question_id) VALUES ("O(n^2), also called quadratic time.",0,141);
INSERT INTO answer(answer, correct, question_id) VALUES ("O(1), also called constant time.",1,141);
INSERT INTO answer(answer, correct, question_id) VALUES ("set",0,142);
INSERT INTO answer(answer, correct, question_id) VALUES ("list",1,142);
INSERT INTO answer(answer, correct, question_id) VALUES ("None",0,142);
INSERT INTO answer(answer, correct, question_id) VALUES ("dictionary",0,142);
INSERT INTO answer(answer, correct, question_id) VALUES ("class Game.LogicGame(): pass",0,143);
INSERT INTO answer(answer, correct, question_id) VALUES ("def Game(LogicGame): pass",0,143);
INSERT INTO answer(answer, correct, question_id) VALUES ("class Game(LogicGame): pass",1,143);
INSERT INTO answer(answer, correct, question_id) VALUES ("def Game.LogicGame(): pass",0,143);
INSERT INTO answer(answer, correct, question_id) VALUES ("You can assign a name to each of the namedtuple members and refer to them that way, similarly to how you would access keys in dictionary.",0,144);
INSERT INTO answer(answer, correct, question_id) VALUES ("Each member of a namedtuple object can be indexed to directly, just like in a regular tuple.",0,144);
INSERT INTO answer(answer, correct, question_id) VALUES ("namedtuples are just as memory efficient as regular tuples.",0,144);
INSERT INTO answer(answer, correct, question_id) VALUES ("No import is needed to use namedtuples because they are available in the standard library.",1,144);
INSERT INTO answer(answer, correct, question_id) VALUES ("Instance methods can modify the state of an instance or the state of its parent class.",1,145);
INSERT INTO answer(answer, correct, question_id) VALUES ("Instance methods hold data related to the instance.",0,145);
INSERT INTO answer(answer, correct, question_id) VALUES ("An instance method is any class method that doesn't take any arguments.",0,145);
INSERT INTO answer(answer, correct, question_id) VALUES ("An instance method is a regular function that belongs to a class, but it must return None.",0,145);
INSERT INTO answer(answer, correct, question_id) VALUES ("It protects the data from outside interference.",0,146);
INSERT INTO answer(answer, correct, question_id) VALUES ("A parent class is encapsulated and no data from the parent class passes on to the child class.",0,146);
INSERT INTO answer(answer, correct, question_id) VALUES ("It keeps data and the methods that can manipulate that data in one place.",0,146);
INSERT INTO answer(answer, correct, question_id) VALUES ("It only allows the data to be changed by methods.",1,146);
INSERT INTO answer(answer, correct, question_id) VALUES ("dictionary",0,147);
INSERT INTO answer(answer, correct, question_id) VALUES ("set",0,147);
INSERT INTO answer(answer, correct, question_id) VALUES ("None. You can only build a queue from scratch.",0,147);
INSERT INTO answer(answer, correct, question_id) VALUES ("list",1,147);
INSERT INTO answer(answer, correct, question_id) VALUES ("my_game = class.Game()",0,148);
INSERT INTO answer(answer, correct, question_id) VALUES ("my_game = class(Game)",0,148);
INSERT INTO answer(answer, correct, question_id) VALUES ("my_game = Game()",1,148);
INSERT INTO answer(answer, correct, question_id) VALUES ("my_game = Game.create()",0,148);
INSERT INTO answer(answer, correct, question_id) VALUES ("It creates a path from multiple values in an iterable to a single value.",0,149);
INSERT INTO answer(answer, correct, question_id) VALUES ("It applies a function to each item in an iterable and returns the value of that function.",1,149);
INSERT INTO answer(answer, correct, question_id) VALUES ("It converts a complex value type into simpler value types.",0,149);
INSERT INTO answer(answer, correct, question_id) VALUES ("It creates a mapping between two different elements of different iterables.",0,149);
INSERT INTO answer(answer, correct, question_id) VALUES ("slot",0,150);
INSERT INTO answer(answer, correct, question_id) VALUES ("dictionary",1,150);
INSERT INTO answer(answer, correct, question_id) VALUES ("queue",0,150);
INSERT INTO answer(answer, correct, question_id) VALUES ("sorted list",0,150);
INSERT INTO answer(answer, correct, question_id) VALUES ("A matrix may contain numeric values only.",0,151);
INSERT INTO answer(answer, correct, question_id) VALUES ("A matrix must not be singular.",0,151);
INSERT INTO answer(answer, correct, question_id) VALUES ("A data frame may contain variables that have different modes.",1,151);
INSERT INTO answer(answer, correct, question_id) VALUES ("A data frame may contain variables of different lengths.",0,151);
INSERT INTO answer(answer, correct, question_id) VALUES ("1",0,152);
INSERT INTO answer(answer, correct, question_id) VALUES ("365",1,152);
INSERT INTO answer(answer, correct, question_id) VALUES ("4",0,152);
INSERT INTO answer(answer, correct, question_id) VALUES ("12",0,152);
INSERT INTO answer(answer, correct, question_id) VALUES ("remove()",1,153);
INSERT INTO answer(answer, correct, question_id) VALUES ("erase()",0,153);
INSERT INTO answer(answer, correct, question_id) VALUES ("detach()",0,153);
INSERT INTO answer(answer, correct, question_id) VALUES ("delete()",0,153);
INSERT INTO answer(answer, correct, question_id) VALUES ("height(length(height))",0,154);
INSERT INTO answer(answer, correct, question_id) VALUES ("height[length(height)]",1,154);
INSERT INTO answer(answer, correct, question_id) VALUES ("height[length[height]]",0,154);
INSERT INTO answer(answer, correct, question_id) VALUES ("height(5)",0,154);
INSERT INTO answer(answer, correct, question_id) VALUES ("Var_A!",0,155);
INSERT INTO answer(answer, correct, question_id) VALUES ("\_VarA",0,155);
INSERT INTO answer(answer, correct, question_id) VALUES (".2Var_A",0,155);
INSERT INTO answer(answer, correct, question_id) VALUES ("Var2_A",1,155);
INSERT INTO answer(answer, correct, question_id) VALUES ("A matrix has two dimensions, while an array can have three or more dimensions.",1,156);
INSERT INTO answer(answer, correct, question_id) VALUES ("An array is a subtype of the data frame, while a matrix is a separate type entirely.",0,156);
INSERT INTO answer(answer, correct, question_id) VALUES ("A matrix can have columns of different lengths, but an array's columns must all be the same length.",0,156);
INSERT INTO answer(answer, correct, question_id) VALUES ("A matrix may contain numeric values only, while an array can mix different types of values.",0,156);
INSERT INTO answer(answer, correct, question_id) VALUES ("type",0,157);
INSERT INTO answer(answer, correct, question_id) VALUES ("length",0,157);
INSERT INTO answer(answer, correct, question_id) VALUES ("attributes",0,157);
INSERT INTO answer(answer, correct, question_id) VALUES ("scalar",1,157);
INSERT INTO answer(answer, correct, question_id) VALUES ("BOF(pizza, 5)",0,158);
INSERT INTO answer(answer, correct, question_id) VALUES ("first(pizza, 5)",0,158);
INSERT INTO answer(answer, correct, question_id) VALUES ("top(pizza, 5)",0,158);
INSERT INTO answer(answer, correct, question_id) VALUES ("head(pizza, 5)",1,158);
INSERT INTO answer(answer, correct, question_id) VALUES ("console(-25)",0,159);
INSERT INTO answer(answer, correct, question_id) VALUES ("console(reverse=TRUE)",0,159);
INSERT INTO answer(answer, correct, question_id) VALUES ("history()",0,159);
INSERT INTO answer(answer, correct, question_id) VALUES ("history(max.show = 25)",1,159);
INSERT INTO answer(answer, correct, question_id) VALUES ("Vectors are used only for numeric data, while list are useful for both numeric and string data.",0,160);
INSERT INTO answer(answer, correct, question_id) VALUES ("Vectors and lists are the same thing and can be used interchangeably.",0,160);
INSERT INTO answer(answer, correct, question_id) VALUES ("A vector contains items of a single data type, while a list can contain items of different data types.",1,160);
INSERT INTO answer(answer, correct, question_id) VALUES ("Vectors are like arrays, while lists are like data frames.",0,160);
INSERT INTO answer(answer, correct, question_id) VALUES ("list.objects()",0,161);
INSERT INTO answer(answer, correct, question_id) VALUES ("print.objects()",0,161);
INSERT INTO answer(answer, correct, question_id) VALUES ("getws()",0,161);
INSERT INTO answer(answer, correct, question_id) VALUES ("ls()",1,161);
INSERT INTO answer(answer, correct, question_id) VALUES ("rbind()",0,162);
INSERT INTO answer(answer, correct, question_id) VALUES ("cbind()",1,162);
INSERT INTO answer(answer, correct, question_id) VALUES ("bind()",0,162);
INSERT INTO answer(answer, correct, question_id) VALUES ("coerce()",0,162);
INSERT INTO answer(answer, correct, question_id) VALUES ("cor.test(Var1 ~ Var2)",0,163);
INSERT INTO answer(answer, correct, question_id) VALUES ("cor.test(mydata$(Var1,Var2))",0,163);
INSERT INTO answer(answer, correct, question_id) VALUES ("cor.test(mydata$Var1,mydata$Var2)",1,163);
INSERT INTO answer(answer, correct, question_id) VALUES ("cor.test(mydata$Var1,mydata$Var2)",0,163);
INSERT INTO answer(answer, correct, question_id) VALUES ("data frame: names() and rownames() matrix: colnames() and row.names()",0,164);
INSERT INTO answer(answer, correct, question_id) VALUES ("data frame: names() and row.names() matrix: dimnames() (not sure)",1,164);
INSERT INTO answer(answer, correct, question_id) VALUES ("data frame: colnames() and row.names() matrix: names() and rownames()",0,164);
INSERT INTO answer(answer, correct, question_id) VALUES ("data frame: colnames() and rownames() matrix: names() and row.names()",0,164);
INSERT INTO answer(answer, correct, question_id) VALUES ("connect()",0,165);
INSERT INTO answer(answer, correct, question_id) VALUES ("concat()",0,165);
INSERT INTO answer(answer, correct, question_id) VALUES ("contact()",0,165);
INSERT INTO answer(answer, correct, question_id) VALUES ("c()",1,165);
INSERT INTO answer(answer, correct, question_id) VALUES ("Refers to aesthetics. It includes variable names used to create plots.",0,166);
INSERT INTO answer(answer, correct, question_id) VALUES ("Are used to represent data.",1,166);
INSERT INTO answer(answer, correct, question_id) VALUES ("This parameter is used to alter information represented at x axis.",0,166);
INSERT INTO answer(answer, correct, question_id) VALUES ("It performs the same task as scale_x_continuous but for y axis.",0,166);
INSERT INTO answer(answer, correct, question_id) VALUES ("Refers to aesthetics. It includes variable names used to create plots.",1,167);
INSERT INTO answer(answer, correct, question_id) VALUES ("Are used to represent data.",0,167);
INSERT INTO answer(answer, correct, question_id) VALUES ("This parameter is used to alter information represented at x axis.",0,167);
INSERT INTO answer(answer, correct, question_id) VALUES ("It performs the same task as scale_x_continuous but for y axis.",0,167);
INSERT INTO answer(answer, correct, question_id) VALUES ("package for creating graphics with details from statistical tests included in the information-rich plots themselves.",0,168);
INSERT INTO answer(answer, correct, question_id) VALUES ("is a system for declaratively creating graphics, based on The Grammar of Graphics",1,168);
INSERT INTO answer(answer, correct, question_id) VALUES ("It allows you to draw bar plots, curves, scatter plots, histograms, boxplot and sf objects, then export the graph or retrieve the code to reproduce the graph.",0,168);
INSERT INTO answer(answer, correct, question_id) VALUES ("Ridgeline plots are partially overlapping line plots that create the impression of a mountain range.",0,168);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_bar()",0,169);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_dotplot()",0,169);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_boxplot()",0,169);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_point()",1,169);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_bar()",0,170);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_histogram()",1,170);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_boxplot()",0,170);
INSERT INTO answer(answer, correct, question_id) VALUES ("geom_point()",0,170);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used to test the level of correlation among the variable available in the data set.",0,171);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when we want to plot one continuous variable.",1,171);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when want to see the relationship between two continuous variables.",0,171);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used intensity (density) of colors to display relationship between two or three or many variables in a two dimensional image.",0,171);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used to test the level of correlation among the variable available in the data set.",1,172);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when we want to plot one continuous variable.",0,172);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when want to see the relationship between two continuous variables.",0,172);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used intensity (density) of colors to display relationship between two or three or many variables in a two dimensional image.",0,172);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used to test the level of correlation among the variable available in the data set.",0,173);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when we want to plot one continuous variable.",0,173);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used when want to see the relationship between two continuous variables.",1,173);
INSERT INTO answer(answer, correct, question_id) VALUES ("Is used intensity (density) of colors to display relationship between two or three or many variables in a two dimensional image.",0,173);
INSERT INTO answer(answer, correct, question_id) VALUES ("Generates small multiples, each displaying a different subset of the data.",0,174);
INSERT INTO answer(answer, correct, question_id) VALUES ("it provides a way for package authors to add methods that work like the base plot() function, generating useful default plots with little user interaction.",0,174);
INSERT INTO answer(answer, correct, question_id) VALUES ("Help readers interpret your plots.",0,174);
INSERT INTO answer(answer, correct, question_id) VALUES ("Control the details of how data values are translated to visual properties.",1,174);
INSERT INTO answer(answer, correct, question_id) VALUES ("Generates small multiples, each displaying a different subset of the data.",1,175);
INSERT INTO answer(answer, correct, question_id) VALUES ("it provides a way for package authors to add methods that work like the base plot() function, generating useful default plots with little user interaction.",0,175);
INSERT INTO answer(answer, correct, question_id) VALUES ("Help readers interpret your plots.",0,175);
INSERT INTO answer(answer, correct, question_id) VALUES ("Control the details of how data values are translated to visual properties.",0,175);
INSERT INTO answer(answer, correct, question_id) VALUES ("ANOVAData, anovadata",0,176);
INSERT INTO answer(answer, correct, question_id) VALUES ("VisitPCA, VarX",1,176);
INSERT INTO answer(answer, correct, question_id) VALUES ("VisitPCA, varx",0,176);
INSERT INTO answer(answer, correct, question_id) VALUES ("Xvar, Yvar",0,176);
INSERT INTO answer(answer, correct, question_id) VALUES ("vector(MyList, length = 7)",0,177);
INSERT INTO answer(answer, correct, question_id) VALUES ("coerce(MyList, nrows = 1)",0,177);
INSERT INTO answer(answer, correct, question_id) VALUES ("unlist(MyList)",1,177);
INSERT INTO answer(answer, correct, question_id) VALUES ("coerce(MyList, nrows = 7)",0,177);
INSERT INTO answer(answer, correct, question_id) VALUES ("patchwork",0,178);
INSERT INTO answer(answer, correct, question_id) VALUES ("ggstatsplot",0,178);
INSERT INTO answer(answer, correct, question_id) VALUES ("gganimate",1,178);
INSERT INTO answer(answer, correct, question_id) VALUES ("hrbrthemes",0,178);
INSERT INTO answer(answer, correct, question_id) VALUES ("ggrepel",0,179);
INSERT INTO answer(answer, correct, question_id) VALUES ("ggstatsplot",0,179);
INSERT INTO answer(answer, correct, question_id) VALUES ("ggfx",1,179);
INSERT INTO answer(answer, correct, question_id) VALUES ("hrbrthemes",0,179);
INSERT INTO answer(answer, correct, question_id) VALUES ("tableplot(dataset)",1,180);
INSERT INTO answer(answer, correct, question_id) VALUES ("autolayer(dataset)",0,180);
INSERT INTO answer(answer, correct, question_id) VALUES ("autoplot(datase)",0,180);
INSERT INTO answer(answer, correct, question_id) VALUES ("map_data(dataset)",0,180);

//Users
INSERT INTO user(email, name, nick_name, user_password) VALUES ("ealopezalmira@gmail.com", "Edwin Almira", "edwinalmira", "pass12385");
INSERT INTO user(email, name, nick_name, user_password) VALUES ("Aherrh02@gmail.con", "Alejandro Herrera", "aherrh02", "pass12385");
INSERT INTO user(email, name, nick_name, user_password) VALUES ("ruben.vigil24@gmail.com", "Ruben Vigil", "vigil24", "pass12385");
INSERT INTO user(email, name, nick_name, user_password) VALUES ("cycles.250@gmail.com", "Adilson Arbuez", "cycles", "pass12385");
INSERT INTO user(email, name, nick_name, user_password) VALUES ("amayaricardo2607@gmail.com", "Ricardo Amaya", "richardamaya26", "pass12385");